[workspace]
resolver = "2"
members = [
  "crates/moonmesh-core",
  "crates/moonmesh-identity",
  "crates/moonmesh-protocol",
  "crates/moonmesh-peer",
]

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.1.0"
rust-version = "1.85"

[workspace.dependencies]
moonmesh-core = { path = "crates/moonmesh-core" }
moonmesh-identity = { path = "crates/moonmesh-identity" }
moonmesh-protocol = { path = "crates/moonmesh-protocol" }
moonmesh-peer = { path = "crates/moonmesh-peer" }
